apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
spec:
  replicas: 2
  selector:
    app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      volumes:
        - name: saas20logs
          hostPath:
            path: /mnt
        - name: host-time
          hostPath:
            path : /etc/localtime
        - name: host-timezone
          hostPath:
            path : /etc/timezone
      containers:
        - name: myweb
          image: tomcat:8
          resources:
            limits:
                memory: 1024Mi
            requests:
                memory: 1024Mi
          imagePullPolicy: IfNotPresent
          #env:  #等同于resources设置?
          #  - name : JAVA_OPTS
          #    value: "-Xms1024M -Xmx1024M -XX:PermSize=768M -XX:MaxPermSize=768M -Dcoldfusion.disablejsafe=true"
          volumeMounts:
          - name: saas20logs
            readOnly: false
            mountPath: "/usr/local/tomcat/logs"
          - name: host-time
            mountPath: /etc/localtime
          - name: host-timezone
            mountPath: /etc/timezone
          ports:
          - containerPort: 8080
          env:
          - name: MYSQL_SERVICE_HOST
            value: 'ipaddress'
          - name: MYSQL_SERVICE_PORT
            value: '3306'
