kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grafana
  namespace: ns-monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: images.unovo.com.cn/library/grafana:latest
          imagePullPolicy: IfNotPresent
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GF_AUTH_BASIC_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
            # - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            #   value: Admin
            # does not really work, because of template variables in exported dashboards:
            # - name: GF_DASHBOARDS_JSON_ENABLED
            #   value: "true"
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-persistent-storage
          ports:
            - containerPort: 3000
              protocol: TCP
      volumes:
        - name: grafana-persistent-storage
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  namespace: ns-monitor
  name: grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
  selector:
    app: grafana
    
    
    
    
    
 显示模版地址：https://grafana.com/dashboards/162    
这里存在一些问题后续要继续研究解决。
1、prometheus的数据存储采用emptydir。如果Pod被删除，或者Pod发生迁移，emptyDir也会被删除，并且永久丢失。后续可以在K8S集群外部再配置一个Prometheus系统来永久保存监控数据， 两个prometheus系统之间通过配置job自动进行数据拉取。
2、Grafana的配置数据存储采用emptydir。如果Pod被删除，或者Pod发生迁移，emptyDir也会被删除，并且永久丢失。我们也可以选择将grafana配置在k8s外部，数据源选择K8S集群外部的prometheus即可。
3、关于监控项的报警（alertmanager）尚未配置。
