apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb-saas20
spec:
  replicas: 2
  selector:
    app: myweb-saas20
  template:
    metadata:
      labels:
        app: myweb-saas20
    spec:
      volumes:
        - name: tomcat-logs
          hostPath:
            path: /data/
      containers:
        - name: myweb-saas20
          image: tomcat:8
          volumeMounts:
          - name: tomcat-logs
            readOnly: false
            mountPath: "/usr/local/tomcat/logs"

          ports:
          - containerPort: 8080

